language: php

dist: xenial

before_script:
  - sudo apt-get update
  # Previously installed xpdf libexpat-dev libgif-dev
  - sudo apt-get install -y libfreetype6-dev libjpeg-dev libpng-dev zlib1g-dev gettext build-essential unzip
  - wget http://ftp.debian.org/debian/pool/main/g/giflib/libgif4_4.1.6-11+deb8u1_amd64.deb -O ./libgif4_4.deb
  - wget http://ftp.debian.org/debian/pool/main/g/giflib/libgif-dev_4.1.6-11+deb8u1_amd64.deb -O ./libgif-dev_4.deb
  - sudo apt install -y ./libgif4_4.deb
  - sudo apt install -y ./libgif-dev_4.deb
  #- wget http://www.swftools.org/swftools-0.9.2.tar.gz
  - wget "https://github.com/matthiaskramm/swftools/archive/master.zip" -O swftools.zip
  #- sh -c "tar xzvf swftools-0.9.2.tar.gz && cd swftools-0.9.2 && ./configure && make && sudo make install"
  - sh -c "unzip swftools.zip && cd swftools-master && ./configure && make && sudo make install"
  - composer install --dev --prefer-source

script: ./vendor/bin/phpunit

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
