<?php

/* default/layout/page.twig */
class __TwigTemplate_35e25f1083f396aba3e674aa8078e4da extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = $this->env->loadTemplate("layout/layout.twig");

        $this->blocks = array(
            'frame' => array($this, 'block_frame'),
            'header' => array($this, 'block_header'),
            'content_header' => array($this, 'block_content_header'),
            'footer' => array($this, 'block_footer'),
        );
    }

    protected function doGetParent(array $context)
    {
        return "layout/layout.twig";
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $this->parent->display($context, array_merge($this->blocks, $blocks));
    }

    // line 3
    public function block_frame($context, array $blocks = array())
    {
        // line 4
        echo "    <li><a href=\"";
        echo twig_escape_filter($this->env, $this->env->getExtension('sami')->pathForStaticFile($context, "index.html"), "html", null, true);
        echo "\" target=\"_top\">Frames</a></li>
    <li><a href=\"#\" target=\"_top\">No Frames</a></li>
";
    }

    // line 8
    public function block_header($context, array $blocks = array())
    {
        // line 9
        echo "    <div class=\"header\">
        <ul>
            <li><a href=\"";
        // line 11
        echo twig_escape_filter($this->env, $this->env->getExtension('sami')->pathForStaticFile($context, "classes.html"), "html", null, true);
        echo "\">Classes</a></li>
            ";
        // line 12
        if ($this->getContext($context, "has_namespaces")) {
            // line 13
            echo "                <li><a href=\"";
            echo twig_escape_filter($this->env, $this->env->getExtension('sami')->pathForStaticFile($context, "namespaces.html"), "html", null, true);
            echo "\">Namespaces</a></li>
            ";
        }
        // line 15
        echo "            <li><a href=\"";
        echo twig_escape_filter($this->env, $this->env->getExtension('sami')->pathForStaticFile($context, "interfaces.html"), "html", null, true);
        echo "\">Interfaces</a></li>
            <li><a href=\"";
        // line 16
        echo twig_escape_filter($this->env, $this->env->getExtension('sami')->pathForStaticFile($context, "doc-index.html"), "html", null, true);
        echo "\">Index</a></li>
            ";
        // line 17
        $this->displayBlock("frame", $context, $blocks);
        echo "
        </ul>

        <div id=\"title\">";
        // line 20
        echo twig_escape_filter($this->env, $this->getAttribute($this->getContext($context, "project"), "config", array(0 => "title"), "method"), "html", null, true);
        echo "</div>

        ";
        // line 22
        $this->displayBlock('content_header', $context, $blocks);
        // line 23
        echo "    </div>
";
    }

    // line 22
    public function block_content_header($context, array $blocks = array())
    {
        echo "";
    }

    // line 26
    public function block_footer($context, array $blocks = array())
    {
        // line 27
        echo "    <div id=\"footer\">
        Generated by <a href=\"http://sami.sensiolabs.org/\" target=\"_top\">Sami, the API Documentation Generator</a>.
    </div>
";
    }

    public function getTemplateName()
    {
        return "default/layout/page.twig";
    }

    public function isTraitable()
    {
        return false;
    }

    public function getDebugInfo()
    {
        return array (  95 => 27,  59 => 15,  43 => 9,  142 => 39,  134 => 36,  127 => 35,  123 => 33,  116 => 32,  112 => 30,  103 => 29,  99 => 27,  93 => 25,  86 => 22,  70 => 18,  64 => 16,  53 => 13,  24 => 3,  41 => 8,  39 => 7,  19 => 2,  377 => 58,  361 => 56,  356 => 55,  353 => 54,  348 => 53,  331 => 52,  329 => 51,  327 => 50,  316 => 49,  301 => 46,  289 => 45,  263 => 40,  259 => 39,  256 => 37,  253 => 35,  251 => 34,  234 => 33,  232 => 32,  220 => 31,  209 => 28,  203 => 27,  197 => 26,  183 => 25,  172 => 22,  166 => 21,  160 => 20,  146 => 19,  133 => 16,  131 => 15,  124 => 13,  117 => 11,  115 => 10,  102 => 9,  51 => 12,  40 => 8,  35 => 6,  32 => 4,  23 => 4,  17 => 1,  108 => 32,  101 => 28,  97 => 26,  88 => 27,  85 => 6,  81 => 23,  77 => 23,  62 => 16,  60 => 15,  56 => 14,  50 => 11,  47 => 11,  44 => 9,  38 => 7,  78 => 21,  74 => 20,  69 => 19,  58 => 13,  54 => 12,  48 => 9,  29 => 3,  92 => 26,  89 => 25,  82 => 8,  79 => 22,  73 => 5,  68 => 17,  66 => 18,  63 => 18,  45 => 10,  42 => 9,  36 => 7,  31 => 5,  20 => 8,  49 => 12,  37 => 6,  33 => 10,  30 => 4,  27 => 6,  26 => 3,);
    }
}
